# Complete crop information database matching your frontend

CROP_DETAILS = {
    'rice': {
        'id': 'rice',
        'name': 'Rice',
        'scientificName': 'Oryza sativa',
        'emoji': '🌾',
        'season': 'Kharif',
        'duration': '120-150d',
        'price': '₹2,500/q',
        'yield': '45q/ac',
        'cost': '₹40,000',
        'revenue': '₹1,12,500',
        'profit': '₹72,500',
        'desc': 'Rice is the staple food crop feeding half the world. Thrives in warm, humid climates with flooded fields.',
        'cultivation': 'Prepare puddled field → Transplant 21-day seedlings at 20×15cm → Maintain 2-3 inch water → Apply fertilizers in 3 splits',
        'fertilizers': 'Basal: DAP 50kg + MOP 17kg | Top-1 (21d): Urea 43kg | Top-2 (45d): Urea 43kg',
        'selling': 'FCI procurement centers (MSP ₹2,183/q) • Rice mills • State agencies • APMC mandis • Export markets'
    },
    'maize': {
        'id': 'maize',
        'name': 'Maize',
        'scientificName': 'Zea mays',
        'emoji': '🌽',
        'season': 'Kharif/Rabi',
        'duration': '90-120d',
        'price': '₹2,100/q',
        'yield': '35q/ac',
        'cost': '₹28,000',
        'revenue': '₹73,500',
        'profit': '₹45,500',
        'desc': 'Versatile C4 crop for food, feed, and industrial uses. Modern hybrids give excellent yields.',
        'cultivation': 'Make ridges 60cm apart → Dibble seeds 5-7cm deep → Irrigate at knee-high/flowering/grain filling',
        'fertilizers': 'Basal: DAP 50kg + MOP 12kg | Top-1 (30d): Urea 65kg | Top-2 (50d): Urea 43kg',
        'selling': 'Poultry feed manufacturers • Starch industries • Cattle feed mills • Corn flakes companies'
    },
    'chickpea': {
        'id': 'chickpea',
        'name': 'Chickpea',
        'scientificName': 'Cicer arietinum',
        'emoji': '🫘',
        'season': 'Rabi',
        'duration': '100-120d',
        'price': '₹6,000/q',
        'yield': '18q/ac',
        'cost': '₹18,000',
        'revenue': '₹1,08,000',
        'profit': '₹90,000',
        'desc': 'Important pulse crop and protein source. Nitrogen-fixing legume improving soil fertility.',
        'cultivation': 'Line sowing at 30×10cm → Treat seeds with Rhizobium → 1-2 light irrigations',
        'fertilizers': 'Basal: DAP 40kg + MOP 25kg + Rhizobium culture | Foliar: 2% DAP spray at flowering',
        'selling': 'Dal mills • Government MSP procurement • APMC mandis • Export markets (Kabuli)'
    },
    'kidneybeans': {
        'id': 'kidneybeans',
        'name': 'Kidney Beans',
        'scientificName': 'Phaseolus vulgaris',
        'emoji': '🫘',
        'season': 'Kharif/Rabi',
        'duration': '90-120d',
        'price': '₹8,000/q',
        'yield': '12q/ac',
        'cost': '₹20,000',
        'revenue': '₹96,000',
        'profit': '₹76,000',
        'desc': 'High-value pulse crop rich in protein and fiber. Growing demand in domestic and export markets.',
        'cultivation': 'Line sowing at 45×10cm → Rhizobium treatment → Irrigate at flowering and pod development',
        'fertilizers': 'Basal: DAP 30kg + MOP 20kg + Rhizobium | Top: Urea 20kg at flowering',
        'selling': 'Dal mills • Export markets • Canned food industry • Retail markets'
    },
    'pigeonpeas': {
        'id': 'pigeonpea',
        'name': 'Pigeon Pea',
        'scientificName': 'Cajanus cajan',
        'emoji': '🫘',
        'season': 'Kharif',
        'duration': '150-180d',
        'price': '₹6,500/q',
        'yield': '12q/ac',
        'cost': '₹18,000',
        'revenue': '₹78,000',
        'profit': '₹60,000',
        'desc': 'Important pulse crop known as Arhar/Tur. Deep root system makes it drought tolerant.',
        'cultivation': 'Line sowing at 90×20cm → Minimal irrigation → Intercrop with short duration crops',
        'fertilizers': 'Basal: DAP 30kg + MOP 15kg + Rhizobium culture | No top dressing needed',
        'selling': 'Dal mills • Government MSP procurement • APMC mandis • Wholesale pulse traders'
    },
    'mothbeans': {
        'id': 'mothbeans',
        'name': 'Moth Beans',
        'scientificName': 'Vigna aconitifolia',
        'emoji': '🫘',
        'season': 'Kharif',
        'duration': '75-90d',
        'price': '₹5,500/q',
        'yield': '8q/ac',
        'cost': '₹12,000',
        'revenue': '₹44,000',
        'profit': '₹32,000',
        'desc': 'Drought-resistant pulse crop suitable for arid regions. Good source of protein.',
        'cultivation': 'Broadcast or line sowing → Minimal irrigation → Harvest when pods dry',
        'fertilizers': 'Basal: DAP 20kg + Rhizobium | Minimal fertilizer requirements',
        'selling': 'Local markets • Dal mills • Animal feed industry'
    },
    'mungbean': {
        'id': 'greengram',
        'name': 'Green Gram',
        'scientificName': 'Vigna radiata',
        'emoji': '🟢',
        'season': 'Kharif/Rabi',
        'duration': '60-70d',
        'price': '₹7,000/q',
        'yield': '6q/ac',
        'cost': '₹14,000',
        'revenue': '₹42,000',
        'profit': '₹28,000',
        'desc': 'Short duration pulse known as Moong. Highly nutritious and easily digestible. Used for dal and sprouts.',
        'cultivation': 'Line sowing at 30×10cm → Rhizobium inoculation → One light irrigation',
        'fertilizers': 'Basal: DAP 25kg + MOP 12kg + Rhizobium culture | No top dressing needed',
        'selling': 'Dal mills • Government MSP procurement • APMC mandis • Health food stores'
    },
    'blackgram': {
        'id': 'blackgram',
        'name': 'Black Gram',
        'scientificName': 'Vigna mungo',
        'emoji': '⚫',
        'season': 'Kharif/Rabi',
        'duration': '70-90d',
        'price': '₹7,500/q',
        'yield': '8q/ac',
        'cost': '₹16,000',
        'revenue': '₹60,000',
        'profit': '₹44,000',
        'desc': 'Important pulse known as Urad. Short duration allows multiple crops. Used for dal and papad.',
        'cultivation': 'Line sowing at 30×10cm → Rhizobium inoculation → Light irrigation',
        'fertilizers': 'Basal: DAP 25kg + MOP 12kg + Rhizobium culture | Foliar: DAP spray at flowering',
        'selling': 'Dal mills • Government MSP procurement • APMC mandis • Papad manufacturers'
    },
    'lentil': {
        'id': 'lentil',
        'name': 'Lentil',
        'scientificName': 'Lens culinaris',
        'emoji': '🔴',
        'season': 'Rabi',
        'duration': '110-130d',
        'price': '₹5,800/q',
        'yield': '10q/ac',
        'cost': '₹16,000',
        'revenue': '₹58,000',
        'profit': '₹42,000',
        'desc': 'Important pulse known as Masoor. Cool season crop. High protein content. Quick cooking dal.',
        'cultivation': 'Line sowing at 30×10cm in November → Rhizobium seed treatment → 1-2 light irrigations',
        'fertilizers': 'Basal: DAP 30kg + MOP 15kg + Rhizobium culture | Foliar: DAP spray if needed',
        'selling': 'Dal mills • Government MSP procurement • APMC mandis • Wholesale pulse merchants'
    },
    'pomegranate': {
        'id': 'pomegranate',
        'name': 'Pomegranate',
        'scientificName': 'Punica granatum',
        'emoji': '🍎',
        'season': 'Perennial',
        'duration': '2-3y to bear',
        'price': '₹80/kg',
        'yield': '80q/ac',
        'cost': '₹1,80,000',
        'revenue': '₹6,40,000',
        'profit': '₹4,60,000',
        'desc': 'High-value fruit crop with medicinal properties. Growing export demand. Rich in antioxidants.',
        'cultivation': 'Plant cuttings/grafts at 12×12ft → Drip irrigation → Bahar treatment for controlled flowering',
        'fertilizers': 'Annual per plant: 250g N + 125g P + 250g K | Monthly fertigation | Calcium sprays',
        'selling': 'Export markets (Europe, Middle East) • Premium fruit markets • Juice manufacturers'
    },
    'banana': {
        'id': 'banana',
        'name': 'Banana',
        'scientificName': 'Musa paradisiaca',
        'emoji': '🍌',
        'season': 'Year-round',
        'duration': '11-13m',
        'price': '₹25/kg',
        'yield': '450q/ac',
        'cost': '₹1,00,000',
        'revenue': '₹11,25,000',
        'profit': '₹10,25,000',
        'desc': 'One of most important fruit crops with year-round production. Tissue culture ensures disease-free yields.',
        'cultivation': 'Plant tissue culture plants in 60×60cm pits → High density 6×6ft spacing → Monthly de-suckering',
        'fertilizers': 'Monthly: 200g N + 100g P + 300g K per plant per cycle | Micronutrient spray every 60 days',
        'selling': 'Wholesale fruit markets • Retail vendors • Supermarket chains • Export markets'
    },
    'mango': {
        'id': 'mango',
        'name': 'Mango',
        'scientificName': 'Mangifera indica',
        'emoji': '🥭',
        'season': 'Perennial',
        'duration': '3-4y to bear',
        'price': '₹45/kg',
        'yield': '80q/ac',
        'cost': '₹1,50,000',
        'revenue': '₹3,60,000',
        'profit': '₹2,10,000',
        'desc': 'King of fruits with immense commercial value. Multiple varieties for different markets. Export potential for Alphonso.',
        'cultivation': 'Plant grafted saplings at 30×30ft → Regular irrigation in flowering/fruiting → Pest management',
        'fertilizers': 'Annual: 250g N + 125g P + 250g K per tree | Split into 3 applications | Foliar spray',
        'selling': 'Wholesale fruit markets • Retail markets • Export houses (APEDA) • Juice/pulp manufacturers'
    },
    'grapes': {
        'id': 'grapes',
        'name': 'Grapes',
        'scientificName': 'Vitis vinifera',
        'emoji': '🍇',
        'season': 'Perennial',
        'duration': '2-3y to bear',
        'price': '₹70/kg',
        'yield': '120q/ac',
        'cost': '₹2,50,000',
        'revenue': '₹8,40,000',
        'profit': '₹5,90,000',
        'desc': 'Premium fruit crop with excellent export potential. Table grapes fetch high prices. Wine industry consumer.',
        'cultivation': 'Plant grafted vines at 12×6ft → Trellising system → Regular pruning → Bunch management',
        'fertilizers': 'Per acre annual: 80kg N + 60kg P + 120kg K | Monthly fertigation | Micronutrient sprays',
        'selling': 'Export markets (Europe, Middle East) • Wholesale fruit markets • Supermarkets • Wine industries'
    },
    'watermelon': {
        'id': 'watermelon',
        'name': 'Watermelon',
        'scientificName': 'Citrullus lanatus',
        'emoji': '🍉',
        'season': 'Summer',
        'duration': '90-100d',
        'price': '₹12/kg',
        'yield': '200q/ac',
        'cost': '₹35,000',
        'revenue': '₹2,40,000',
        'profit': '₹2,05,000',
        'desc': 'High-value summer fruit with good market demand. Requires warm weather and adequate water.',
        'cultivation': 'Pit sowing at 2×2m spacing → Drip irrigation → Mulching → Support fruits with straw',
        'fertilizers': 'Basal: FYM 10 tons + DAP 40kg + MOP 40kg | Top: Urea 40kg at vine growth',
        'selling': 'Wholesale fruit markets • Retail markets • Juice industry • Export markets'
    },
    'muskmelon': {
        'id': 'muskmelon',
        'name': 'Muskmelon',
        'scientificName': 'Cucumis melo',
        'emoji': '🍈',
        'season': 'Summer',
        'duration': '90-110d',
        'price': '₹20/kg',
        'yield': '120q/ac',
        'cost': '₹30,000',
        'revenue': '₹2,40,000',
        'profit': '₹2,10,000',
        'desc': 'Sweet aromatic fruit with good market price. Requires warm climate and well-drained soil.',
        'cultivation': 'Pit sowing 1.5×1.5m → Drip irrigation → Training on trellis → Harvest at maturity',
        'fertilizers': 'Basal: FYM 8 tons + DAP 35kg + MOP 35kg | Top: Urea 35kg during flowering',
        'selling': 'Wholesale fruit markets • Retail markets • Hotels and restaurants • Export markets'
    },
    'apple': {
        'id': 'apple',
        'name': 'Apple',
        'scientificName': 'Malus domestica',
        'emoji': '🍎',
        'season': 'Perennial',
        'duration': '3-4y to bear',
        'price': '₹60/kg',
        'yield': '100q/ac',
        'cost': '₹2,00,000',
        'revenue': '₹6,00,000',
        'profit': '₹4,00,000',
        'desc': 'Premium temperate fruit crop. Requires cold climate with chilling hours. High initial investment.',
        'cultivation': 'Plant grafted saplings at 15×15ft → Regular pruning and training → Drip irrigation → IPM',
        'fertilizers': 'Annual: 300g N + 150g P + 300g K per tree | Split into 4 applications | Micronutrients',
        'selling': 'Fruit markets • Cold storage units • Supermarket chains • Juice manufacturers • Export (Gulf)'
    },
    'orange': {
        'id': 'orange',
        'name': 'Orange',
        'scientificName': 'Citrus sinensis',
        'emoji': '🍊',
        'season': 'Perennial',
        'duration': '3-4y to bear',
        'price': '₹35/kg',
        'yield': '100q/ac',
        'cost': '₹1,20,000',
        'revenue': '₹3,50,000',
        'profit': '₹2,30,000',
        'desc': 'Important citrus fruit with good market demand. Rich in Vitamin C. Multiple harvest seasons.',
        'cultivation': 'Plant grafted saplings at 20×20ft → Regular irrigation → Pest management → Pruning',
        'fertilizers': 'Annual: 300g N + 150g P + 250g K per tree | Split applications | Micronutrients',
        'selling': 'Fruit markets • Juice industry • Retail markets • Export markets'
    },
    'papaya': {
        'id': 'papaya',
        'name': 'Papaya',
        'scientificName': 'Carica papaya',
        'emoji': '🍈',
        'season': 'Year-round',
        'duration': '10-12m',
        'price': '₹18/kg',
        'yield': '250q/ac',
        'cost': '₹40,000',
        'revenue': '₹4,50,000',
        'profit': '₹4,10,000',
        'desc': 'Fast-growing fruit crop with year-round bearing. Rich in papain enzyme. Good returns.',
        'cultivation': 'Plant at 2×2m spacing → Regular irrigation → Remove male plants → Support tall plants',
        'fertilizers': 'Monthly: 100g N + 50g P + 100g K per plant | Micronutrient sprays',
        'selling': 'Fruit markets • Retail vendors • Enzyme industry • Export markets'
    },
    'coconut': {
        'id': 'coconut',
        'name': 'Coconut',
        'scientificName': 'Cocos nucifera',
        'emoji': '🥥',
        'season': 'Perennial',
        'duration': '4-5y to bear',
        'price': '₹25/nut',
        'yield': '80 nuts/tree',
        'cost': '₹80,000',
        'revenue': '₹2,00,000',
        'profit': '₹1,20,000',
        'desc': 'Versatile plantation crop providing coconut oil, water, copra. Long-term investment with steady returns.',
        'cultivation': 'Plant at 25×25ft → Regular irrigation → Basin management → Intercropping possible',
        'fertilizers': 'Annual: 500g N + 300g P + 1000g K per tree | Split into 4 applications',
        'selling': 'Oil mills • Copra markets • Tender coconut vendors • Export markets'
    },
    'cotton': {
        'id': 'cotton',
        'name': 'Cotton',
        'scientificName': 'Gossypium hirsutum',
        'emoji': '☁️',
        'season': 'Kharif',
        'duration': '150-180d',
        'price': '₹6,500/q',
        'yield': '15q/ac',
        'cost': '₹45,000',
        'revenue': '₹97,500',
        'profit': '₹52,500',
        'desc': 'White gold fiber crop. Bt cotton provides built-in pest resistance. High potassium crucial for quality.',
        'cultivation': 'Sow on ridges 90-120cm apart → Practice IPM → Pick cotton in 3-4 rounds when bolls open',
        'fertilizers': 'Basal: DAP 50kg + MOP 33kg | Top-1 (35d): Urea 33kg | Top-2 (60d): Urea 33kg + MOP 17kg',
        'selling': 'Cotton Corporation of India (CCI) • Ginning mills • Textile mills • APMC cotton mandis'
    },
    'jute': {
        'id': 'jute',
        'name': 'Jute',
        'scientificName': 'Corchorus capsularis',
        'emoji': '🌿',
        'season': 'Kharif',
        'duration': '120-150d',
        'price': '₹4,500/q',
        'yield': '25q/ac',
        'cost': '₹30,000',
        'revenue': '₹1,12,500',
        'profit': '₹82,500',
        'desc': 'Natural fiber crop known as golden fiber. Eco-friendly alternative to synthetic materials.',
        'cultivation': 'Broadcast or line sowing → High humidity required → Retting after harvest → Fiber extraction',
        'fertilizers': 'Basal: Urea 50kg + DAP 40kg + MOP 25kg | Top: Urea 40kg at 30 days',
        'selling': 'Jute mills • Government agencies • Export markets • Packaging industry'
    },
    'coffee': {
        'id': 'coffee',
        'name': 'Coffee',
        'scientificName': 'Coffea arabica',
        'emoji': '☕',
        'season': 'Perennial',
        'duration': '3-4y to bear',
        'price': '₹180/kg',
        'yield': '8q/ac',
        'cost': '₹1,50,000',
        'revenue': '₹1,44,000',
        'profit': '₹-6,000 (initial), ₹80,000 (mature)',
        'desc': 'High-value plantation crop grown in hills. Arabica and Robusta varieties. Export-oriented crop.',
        'cultivation': 'Plant under shade at 2×2m → Organic mulching → Proper drainage → Selective picking',
        'fertilizers': 'Annual: 200g N + 100g P + 200g K per plant | Organic matter addition crucial',
        'selling': 'Coffee Board • Export houses • Roasters and processors • Retail brands'
    }
}

# Mapping dataset labels to our detailed database
LABEL_MAPPING = {
    'rice': 'rice',
    'maize': 'maize',
    'chickpea': 'chickpea',
    'kidneybeans': 'kidneybeans',
    'pigeonpeas': 'pigeonpeas',
    'mothbeans': 'mothbeans',
    'mungbean': 'mungbean',
    'blackgram': 'blackgram',
    'lentil': 'lentil',
    'pomegranate': 'pomegranate',
    'banana': 'banana',
    'mango': 'mango',
    'grapes': 'grapes',
    'watermelon': 'watermelon',
    'muskmelon': 'muskmelon',
    'apple': 'apple',
    'orange': 'orange',
    'papaya': 'papaya',
    'coconut': 'coconut',
    'cotton': 'cotton',
    'jute': 'jute',
    'coffee': 'coffee'
}